name: JSON values prefixer
description: Prefix all values of a JSON array
inputs:
  file_path:
    description: The JSON file path
    required: true
  prefix:
    description: The prefix
    required: true
  key:
    description: |
      Prefix all values corresponding the a certain key.
      Can be used if your JSON array contains objects.
    required: false
runs:
  using: node16
  main: dist/index.js
